### ISSUE TITLE
[RFC] Supporting promises by supplying closure

### ISSUE THREAD

**Issue by sfdctaka** [salesforce/nimbus#107]
Nimbus supports promises in addition to callbacks as means to notify caller the completion of called functions.  Promises get generated when native method implementations have return values.  Callbacks get generated when native method implementations take closures as the method parameters.

We like to support scenarios where a native method won't have a synchronous return value but asynchronously notify the caller later with a useful data, or state, or an error.  Promise fits nicely to support such scenarios.  It is a modern approach to asynchronous programming in Javascript.

This RFC explores how promise can be generated by Nimbus in addition to the current method, for both iOS and Android.  For both of these platforms what would be common to generate Javascript promises when there are no return values by methods is that a closure needs to be provided as the last parameter of native methods.

### iOS
In addition to the above, iOS would require an extra parameter at bind time to explicitly tell Nimbus if the closure provided as the last parameter of a method is to be treated as promise.  The default is set to callback and is not necessary to be explicitly be set.
```
class MyPlugin {
  func foo(completion: (String) -> Void) {
   ...
  }
}
enum TrailingClosure {
  case .callback, .promise
}
c.bind(MyPlugin.foo, "foo", .promise)
```

### Android
Nimbus for Android uses annotation processor to generate Kotlin code that wraps bind target so it is there a method should be marked that its last closure should be treated as promise using `promisifyClosure` boolean flag.
```
@ExtensionMethod(promisifyClosure = true)
fun getDeviceDesignLocation(arg: (param0: String) -> Unit) {
       arg("Mountain View, CA")
}
```
Implementation wise, annotation processor adds new method to wrapped bing target class called `getMethodsWithClosuresToPromisify`.  This was done to pass metadata of the target class's methods to Javascript so that nimbus.js can determine which methods should be promisif-ied during nimbus.js runs `promisify()`.  I considered making `getMethodsWithClosuresToPromisify` more generic so that it can be used to pass other metadata as well.  But future proofing at this time felt little premature and went for the simplest implementation to promisify-ing native methods with closures.

### Promise Dict
In supporting promises I tried to use existing facility as much as possible: promise dict, `resolvePromise` method in nimbus.js core.

### What Can Be Improved
It felt during this spike when I was working on it that even before expanding the support of promise in Nimbus code is tending to favor resolving promise and not so much rejecting.  Nimbus could improve if we can put more places where promise could also be rejected.  Maybe it could be improved by passing two closures, one for resolve and another for reject, so either one can be called at appropriate time instead of relying on resolve chain failing at some point to bubble up an error.

### WIP PR
Above could be understood likely more by looking at the code.  Here is a work in progress:
https://github.com/salesforce/nimbus/pull/106

**Comment by threeve** [comment]
This approach looks good to me. A couple of pieces of feedback:

"promisifyClosure" is perhaps not very clear to users writing plugin code. I'm not sure what is best, but maybe we can explore something along the lines of `trailingClosureArg = Promise` similar to iOS? ¯\_(ツ)_/¯ 

Also can you expand a little bit on `getMethodsWithClosuresToPromisify`? I looked at the code but I'm still having a bit of trouble following the intent of how this works.

Thanks!

**Comment by paultiarks** [comment]
I think this looks good.

My only feedback would be to echo Jason's comment about `promisifyClosure = true`. It doesn't seem very clear that it's referring to the trailing closure or what the effect of it will be.

**Comment by sfdctaka** [comment]
@threeve 

`getMethodsWithClosuresToPromisify` is used only for Android.  It is a method that's bootstrapped when Nimbus.js is initializing.  During the initialization Nimbus.js's `promisify()` method is called. `promisify` needs to know which of the plugin's methods should return promises or otherwise promises are only for plugin's methods with return values.  By calling `getMethodsWithClosuresToPromisify`, `promisify()` gets the metadata of plugin's method, that is, list of methods that were annotated with `promisifyClosure = true`.  With that `promisify` on methods with `promisifyClosure = true` can leverage the `promises` dict in Nimbus.js and follow similar coding pattern how iOS creates and executes promises.

Jason, @paultiarks 
I will change the annotation parameter name to `trailingClosureArg`.

**Comment by sfdctaka** [comment]
`getMethodsWithClosuresToPromisify()` has now changed the name to `getExtensionMetadata()`.  It was changed so that instead of returning a comma separated string of the names of closures that need to be promisified(instead of callbacks) `getExtensionMetadata()` is to be used, for Android, to pass metadata to JS in a dict.  This dict will contain an array property called `trailingClosuresAsPromises`.

`promisifyClosure = true` has been changed.  It is now `trailingClosure` in both iOS and Android and it takes an enum, `callback` or `promise`, to explicitly set that a closure should be promisified or not.

**Comment by sfdctaka** [comment]
https://github.com/salesforce/nimbus/pull/106
