### ISSUE TITLE
[RFC] Supporting reject state for promise created with trailing closure

### ISSUE THREAD

**Issue by sfdctaka** [salesforce/nimbus#116]
Nimbus currently has a way to turn a native method into Javascript method that returns a promise.  For example let's say that we have a method `foo` in iOS:
```
func foo(@escaping callback: (success: String)->Void) {...}
```
and a counterpart in Android:
```
func foo(callback: (success: String)->Unit) {...}
```
For these two methods to be converted into a method that returns a promise in Javascript we need to bind `foo`, for iOS, and indicate that the closure that was passed as a parameter is for promise:
```
connection.bind(foo, as: "foo", trailingClosure: .promise)
```
And for Android we need to annotate `foo` with:
```
@ExtensionMethod(trailingClosure = TrailingClosure.PROMISE)
func foo(callback:(success:String)-> Unit) {...}
```
In Javascript the above would translate into code like this:
```
const promise = foo()
```
But because this promise currently only supports the resolve state but not the reject state it is only then-able:
```
// Doable:
foo().then((success) -> {console.log(success);})
// Not doable:
foo().catch((error) -> {console.log(error);})
// Also not doable:
foo().then((success) -> {console.log(success);}).catch((error) -> {console.log(error);})
```

This RFC lists and explores 3 distinct approaches to support reject state in Nimbus.

**(1) Method that Throws**
If a method is declared to throw and is designated as a trailing closure,
in iOS:
```
func foo(@escaping callback: (success: String) -> ()) throws {...}
connection.bind(foo, as: "foo", trailingClosure: .promise)
```
in Android:
```
@Throws(IOException::class)
@ExtensionMethod(trailingClosure = TrailingClosure.PROMISE)
fun foo(callback: (success: String) -> Unit) {...}
```
then we can consider that promise for these methods will need to support both resolve and reject. All exceptions will be converted into 'something'(string message??).

Pro: Fairly easy to implement
Con: Exception thrown will lose information when it gets to Javascript as a string message. What type of data should reject state pass back??

**(2) Closure with Two Arguments**
If a method is passed a closure with two arguments and this closure is indicated as promise
in iOS:
```
func foo(@escaping callback: (success: String?, error: String?) -> ()) {...}
connection.bind(foo, as: "foo", trailingClosure: .promise)
```
in Android:
```
@ExtensionMethod(trailingClosure = TrailingClosure.PROMISE)
fun foo(callback: (success: String?, error: String?) -> ()) {...}
```
then we can use this same closure to callback for both resolved and rejected states.  The distinction for the two states are made by one of the arguments to the closure being a null but not both.

Pro: Fairly easy to implement
Con: Should the type for error parameter be constrained to specific type???

**(3) Second Closure As Parameter**
If a method is passed **two** closures and these closures are marked for the promise's resolve and reject callbacks,
in iOS:
```
func foo(@escaping success: (String) -> (), @escaping error: (String) -> ()) {...}
connection.bind(foo, as: "foo", trailingClosure: .promiseResolveAndReject)
```
in Android:
```
@ExtensionMethod(trailingClosure = TrailingClosure.PROMISE_RESOLVE_AND_REJECT)
fun foo(success: (String) -> Unit, error: (String) -> Unit) {...}
```
then we can use respective closure to notify resolve and reject states.

Pro: Easier to read than the previous 2 approaches.
Con: More code to write than the previous 2 approaches.

**Comment by threeve** [comment]
Great RFC! Would you be able to copy this into a markdown document (perhaps in `/docs/site/rfcs`) and making a PR for it? That way once we make a decision we'll have a record of it in the docs. Also it's easier to comment on a PR than in an issue.

My preference is toward option 1. Throwing an error is the most natural thing for a native dev to do. Another alternative that works for swift but maybe not kotlin (yet) is having a single-arg callback where the callback argument is a `Result`, with the success case mapping to promise resolve and failure case mapping to promise reject. But going with `throws` is probably the simplest thing to do for now.

I think passing only the error message is fine for now, down the road if we wish we could add an enhanced Error protocol such that if the caught extension implements it we can pass across a structured error object rather than just a string message, but just a string is a fine place to start imho.

**Comment by sfdctaka** [comment]
@threeve Thanks, and will do the markdown!

**Comment by AdamLiechty** [comment]
With option 1, would this prevent asynchronous errors from being possible (i.e. errors that are not generated on the current thread when the function is called, but rather after some other native callback is invoked)?

With option 2, the order of `success` and `error` params is the opposite of the error-first convention used by NodeJS [(e.g. fs.stat)](https://nodejs.org/dist/latest-v13.x/docs/api/fs.html#fs_fs_stat_path_options_callback). Does this matter?

**Comment by sfdctaka** [comment]
@AdamLiechty With option1 asynchronous error should be possible because native and Javascript aren't tightly coupled.  Nimbus core(nimbus.js) keeps a dictionary of promise that can be called by any thread from the native side so long as it passes to Javascript a valid ID of a promise.

I have already implemented this feature here[https://github.com/salesforce/nimbus/pull/118] using option 1.  

As for option 2, we don't have strict standard yet, like NodeJS, if error should come first.  I think this is a good point to keep in mind moving forward as we make enhancements to Nimbus.

**Comment by sfdctaka** [comment]
After a discussion with the team I am reverting the change that I made to create a promise with trailing closure.  The reason is because when the async job is run there is no way to bubble back the error.

☝️  @AdamLiechty 👇 

For now we will only support callbacks as we had from the start.  And in the future we will revisit on how we can create promise using trailing closure or through other means.  In the meantime, if there is an absolute need for promise to be returned to notify the caller instead of callback, then, the caller side should implement a method where nimbus plugin API method that expects callback be wrapped inside a promise.

**Comment by AdamLiechty** [comment]
@sfdctaka thanks for the heads up. I'll give some thought to the best path forward without this feature for now.
