### ISSUE TITLE
Nimbus is nesting the global nimbus variable when attaching to webview

### ISSUE THREAD

**Issue by paultiarks** [salesforce/nimbus#84]
Currently when attaching a nimbus instance to a webview, the nimbus global object is being set as nested inside another global object called `nimbus`

<img width="704" alt="Screen Shot 2019-09-04 at 3 41 34 PM" src="https://user-images.githubusercontent.com/331388/64289972-cf007300-cf2a-11e9-902c-971227ef5172.png">

The global nimbus instance shouldn't be nested and should be available like below:

<img width="714" alt="Screen Shot 2019-09-04 at 3 43 34 PM" src="https://user-images.githubusercontent.com/331388/64290066-03742f00-cf2b-11e9-8133-f68066aa5b79.png">

**Comment by threeve** [comment]
Fixed by #89
