### ISSUE TITLE
Support binding JS functions that return a Promise as native functions that accept a completion

### ISSUE THREAD

**Issue by AdamLiechty** [salesforce/nimbus#98]
Nimbus currently provides great abstractions via plugins that allow Javascript in the web view to call into native code and receive a `Promise` that resolves when the native execution is complete, e.g.:

```swift
let connection = webView.addConnection(to: self, as: "MyPlugin")
connection.bind(MyPlugin.myFunction, as "myFunction")
```

```js
window.__nimbus.plugins.MyPlugin.myFunction(arg1, arg2).then(...)
```

# Proposal

It would be great to symmetrically support native code calling into Javascript functions where a `Promise` is returned, e.g.:

### Javascript
```js
const { plugins } = window.__nimbus
const MyPlugin = plugins.MyPlugin || (plugins.MyPlugin = {})
MyPlugin.doSomething = (arg1, ...) => {
  return new Promise(...)
}
```

### Swift
```swift
func doSomething(arg1: A1, ..., promiseCompletion: @escaping (error: Error?, result: R?) -> Void) {
  connection.invoke("doSomething", with: arg1, ..., promiseCompletion)
}

doSomething("myArg") { err, result in
  print(result) // or handle error if Promise rejected
}
```

### Kotlin
```kotlin
@ExtensionMethod(BindingType.PromisedJavascript)
fun doSomething(arg1: A1, promiseCompletion: (String?, R?) -> Unit) {}

doSomething { err, result ->
  ...
}
```

The above is one possible syntax for hooking up a native function to a Promise-returning JS function, but there may be better or simpler ways of exposing this.

This could abstract the following:
1. `webView.evaluateJavascript` calling a utility function in the Nimbus JS
2. utility JS function in turn calls `__nimbus.plugins.MyPlugin.doSomething`, `then`/`catch`ing the returned Promise. This utility function could have some error handling in case `__nimbus.plugins.MyPlugin` or `__nimbus.plugins.MyPlugin.doSomething` is undefined.
3. These `then`/`catch` functions send a `postMessage` that the Nimbus `Connection`'s `ConnectionMessageHandler` listens
4. The corresponding `promiseCompletion` is invoked.

Just as Nimbus JS currently manages a set of in-flight Promises, Nimbus native's `Connection` would now have to manage a set of in-flight completion handlers, and clean them up when:
1. the corresponding Promise resolves, or
2. the web view navigates elsewhere before the corresponding Promise resolves/rejects, so that it does not have an opportunity to complete.

## Out of scope
Waiting for JS functions to be available.  The mechanism by which the native code knows that a particular JS function is now available on the `window` object is beyond the scope of Nimbus. The app consuming Nimbus needs its own mechanism to determine this, if necessary.

**Comment by threeve** [comment]
Closing this issue since the relevant functionality has been implemented.
